---
abstract: 'A command line tool for launching a POE::Component::Server::IRC instance'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::More: 0.47
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pocosi
no_index:
  directory:
    - t
    - utils
    - example
requires:
  Class::Load: 0.06
  Data::Dump: 0
  IO::WrapOutput: 0.02
  IRC::Utils: 0.10
  JSON::XS: 0
  Module::Pluggable: 0
  POE: 1.310
  POE::Component::Server::IRC: 1.48
  Proc::Daemon: 0.02
  Term::ANSIColor: 0
  Term::Cap: 1.10
  Term::ReadKey: 2.21
  YAML::XS: 0
  perl: 5.008
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Pocosi
  homepage: http://search.cpan.org/dist/App-Pocosi/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/app-pocosi.git
version: 0.02
x_authority: cpan:HINRIK
